"use client";

import { store } from "@/redux/store";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { useState } from "react";
import SignInButton from "@/sections/ParentLayout/SignInOrOutButton";
import { Toaster } from "react-hot-toast";
import Role from "@/sections/firstPage/Role";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [showSignInComponent, setShowSignInComponent] = useState(false);
  // console.log(
  //   "🚀 ~ file: page.js:8 ~ FirstPage ~ showSignInComponent:",
  //   showSignInComponent
  // );

  return (
    <html lang="en">
      <Provider store={store}>
        <body
          className={`${inter.className} h-screen w-full border-[1px] border-gray-400 flex items-center justify-center flex-col `}
        >
          <div
            aria-label="header"
            className={`${""} w-full h-[10%] flex items-center justify-between gap-5 py-2 px-5 border-[1px] border-gray-400 relative`}
          >
            <div
              aria-label="logo"
              className={`${""} w-[200px] h-full flex items-center justify-center gap-5 `}
            >
              Logo
            </div>
            <div
              aria-label="right side"
              className={`${""} w-auto h-full flex items-center justify-center gap-5 `}
            >
              <div aria-label="role" className={`${""} `}>
                <Role />
              </div>
              <div aria-label="signInButton container" className={`${""} `}>
                <SignInButton />
              </div>
            </div>
            <Toaster />
          </div>
          <div
            aria-label="main"
            className={`${""} w-full h-[90%] flex items-center justify-center gap-5 flex-col border-[1px] border-gray-400`}
          >
            {children}
          </div>
        </body>
        {/* <div>{children}</div> */}
      </Provider>
    </html>
  );
}
